services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $projectDir: '%kernel.project_dir%'
      $prettyUrlsRoutePrefix: '%easy_admin_pretty_urls.route_prefix%'
      $prettyUrlsDefaultDashboard: '%easy_admin_pretty_urls.default_dashboard%'

  MarcinJozwikowski\EasyAdminPrettyUrls\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - 'EasyAdminPrettyUrlsBundle.php'

  EasyCorp\Bundle\EasyAdminBundle\Router\AdminUrlGenerator:
    arguments:
      - '@EasyCorp\Bundle\EasyAdminBundle\Provider\AdminContextProvider'
      - '@MarcinJozwikowski\EasyAdminPrettyUrls\Routing\PrettyUrlsGenerator'
      - '@EasyCorp\Bundle\EasyAdminBundle\Registry\DashboardControllerRegistry'
      - '@EasyCorp\Bundle\EasyAdminBundle\Registry\CrudControllerRegistry'

  MarcinJozwikowski\EasyAdminPrettyUrls\Routing\PrettyRoutesLoader:
    tags: [routing.loader]
